name: ml_project_template
global:
  env: prd
  db: BIZ_ML
  workgroup: curationlab

  s3:
    base_output: s3://your-bucket/output
    tmp_output: s3://your-bucket/tmp

  athena:
    tables:
      customer: TEST
      history: HISTORY_TABLE  # 예시 추가

logging:
  log_file: logs/pipeline.log
  level: INFO

paths:
  project_dir: /Users/databiz/workspace/ml_project_template

dag:
  preprocess:
    script: steps/preprocess/preprocess.py
    config: configs/step_params/preprocess.yaml

  train:
    script: steps/train/train.py
    config: configs/step_params/train.yaml
    depends_on: [preprocess]

  inference:
    script: steps/inference/inference.py
    config: configs/step_params/inference.yaml
    depends_on: []