logging:
  log_file: logs/pipeline.log
  level: INFO

paths:
  project_dir: /Users/databiz/workspace/ml_project_template

dag:
  train:
    script: steps/train/train.py
    config: configs/train.yaml

  inference:
    script: steps/inference/inference.py
    config: configs/inference.yaml